/* generated by tools/gen_emoji.py - do not edit */
#pragma once
#include "lvgl.h"

extern const lv_image_dsc_t emoji_heart;
extern const lv_image_dsc_t emoji_up;
extern const lv_image_dsc_t emoji_down;
extern const lv_image_dsc_t emoji_joy;
