#!/usr/bin/env python3
"""Embed a microWakeWord streaming .tflite into a firmware C file.

Usage: tflite_to_c.py <model.tflite> <slot: wake|confirm> <cutoff 0..1>
Writes the C source to stdout; redirect into
firmware/main/voice_model_<slot>.c. The firmware only sees the four
symbols below, so swapping a model is a regeneration, never a code edit.
A missing/empty model file is valid for the confirm slot: emit with
/dev/null to produce the zero-length placeholder (VAD fallback).
"""
import os
import sys


def main() -> None:
    if len(sys.argv) != 4 or sys.argv[2] not in ("wake", "confirm"):
        sys.exit(__doc__)
    path, slot, cutoff = sys.argv[1], sys.argv[2], float(sys.argv[3])
    if not 0.0 < cutoff < 1.0:
        sys.exit("cutoff must be between 0 and 1")
    data = open(path, "rb").read() if os.path.getsize(path) else b""
    name = os.path.splitext(os.path.basename(path))[0] if data else "none"

    print(f"/* Generated by tools/wakeword/tflite_to_c.py from {os.path.basename(path)}")
    print(f" * ({len(data)} bytes). Do not edit; regenerate to change the word. */")
    print('#include "voice_models.h"')
    print()
    print(f'const char voice_model_{slot}_name[] = "{name}";')
    print(f"const float voice_model_{slot}_cutoff = {cutoff:.3f}f;")
    print(f"const unsigned int voice_model_{slot}_len = {len(data)};")
    if not data:
        print(f"const unsigned char voice_model_{slot}_data[1] = {{0}};")
        return
    print(f"const unsigned char voice_model_{slot}_data[] "
          "__attribute__((aligned(16))) = {")
    for i in range(0, len(data), 12):
        row = ", ".join(f"0x{b:02x}" for b in data[i:i + 12])
        print(f"    {row},")
    print("};")


if __name__ == "__main__":
    main()
