per_listener_settings false
allow_anonymous false
password_file /etc/mosquitto/pipvoice/passwd
acl_file /etc/mosquitto/pipvoice/acl

listener 1883 127.0.0.1

listener 8883
certfile /etc/mosquitto/certs/server.crt
keyfile  /etc/mosquitto/certs/server.key
