/* Generated by tools/wakeword/tflite_to_c.py from null
 * (0 bytes). Do not edit; regenerate to change the word. */
#include "voice_models.h"

const char voice_model_confirm_name[] = "none";
const float voice_model_confirm_cutoff = 0.850f;
const unsigned int voice_model_confirm_len = 0;
const unsigned char voice_model_confirm_data[1] = {0};
