/* Embedded microWakeWord streaming models (int8 TFLite), generated by
 * tools/wakeword/tflite_to_c.py - see tools/wakeword/README.md for the
 * train/export loop. Slots, not words: "wake" is whatever phrase opens
 * the voice flow (hey_jarvis stand-in until the hey_pip model is
 * trained), "confirm" is the answer word. A zero-length confirm model
 * means "not trained yet" and voice.c falls back to energy VAD (any
 * speech in the answer window counts as yes). */
#pragma once

#ifdef __cplusplus
extern "C" {
#endif

extern const char          voice_model_wake_name[];
extern const float         voice_model_wake_cutoff;     /* 0..1 */
extern const unsigned int  voice_model_wake_len;
extern const unsigned char voice_model_wake_data[];

extern const char          voice_model_confirm_name[];
extern const float         voice_model_confirm_cutoff;
extern const unsigned int  voice_model_confirm_len;
extern const unsigned char voice_model_confirm_data[];

#ifdef __cplusplus
}
#endif
