#!/usr/bin/env python3
"""Bake Twemoji PNGs into LVGL 9 C arrays (RGB565A8, little-endian).

Sources live in emoji_src/ (72x72 PNGs, committed so builds never need the
network; originally from the Twemoji CDN, CC-BY 4.0). Output goes to
main/ui/assets/ as one .c per emoji plus emoji_assets.h, all committed —
this script only needs re-running when the set changes.

Usage: python3 gen_emoji.py     (needs Pillow; the server venv has it)
"""
import os

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "emoji_src")
OUT = os.path.join(HERE, "..", "main", "ui", "assets")
SIZE = 64

# reaction key -> twemoji codepoint file
EMOJI = {"heart": "2764", "up": "1f44d", "down": "1f44e", "joy": "1f602"}


def resize_rgba(img: Image.Image, size: int) -> Image.Image:
    """LANCZOS on premultiplied alpha: avoids dark fringes at glyph edges."""
    pre = img.convert("RGBA")
    px = pre.load()
    for y in range(pre.height):
        for x in range(pre.width):
            r, g, b, a = px[x, y]
            px[x, y] = (r * a // 255, g * a // 255, b * a // 255, a)
    small = pre.resize((size, size), Image.LANCZOS)
    px = small.load()
    for y in range(size):
        for x in range(size):
            r, g, b, a = px[x, y]
            if a:
                px[x, y] = (min(r * 255 // a, 255), min(g * 255 // a, 255),
                            min(b * 255 // a, 255), a)
    return small


def emit(key: str, img: Image.Image) -> None:
    rgb, alpha = bytearray(), bytearray()
    for r, g, b, a in img.getdata():
        v = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
        rgb += bytes((v & 0xFF, v >> 8))          # RGB565 little-endian
        alpha.append(a)
    data = bytes(rgb + alpha)                     # color plane, then A8 plane
    lines = []
    for i in range(0, len(data), 16):
        lines.append("    " + "".join(f"0x{b:02x}," for b in data[i:i + 16]))
    body = "\n".join(lines)
    with open(os.path.join(OUT, f"emoji_{key}.c"), "w") as f:
        f.write(f"""/* generated by tools/gen_emoji.py - do not edit */
#include "lvgl.h"

static const uint8_t emoji_{key}_map[] = {{
{body}
}};

const lv_image_dsc_t emoji_{key} = {{
    .header = {{ .magic = LV_IMAGE_HEADER_MAGIC,
                .cf = LV_COLOR_FORMAT_RGB565A8,
                .w = {SIZE}, .h = {SIZE}, .stride = {SIZE * 2} }},
    .data_size = sizeof(emoji_{key}_map),
    .data = emoji_{key}_map,
}};
""")


def main() -> None:
    os.makedirs(OUT, exist_ok=True)
    for key, cp in EMOJI.items():
        img = resize_rgba(Image.open(os.path.join(SRC, cp + ".png")), SIZE)
        emit(key, img)
        print(f"emoji_{key}.c  ({SIZE}x{SIZE} RGB565A8, {SIZE*SIZE*3} bytes)")
    with open(os.path.join(OUT, "emoji_assets.h"), "w") as f:
        f.write("/* generated by tools/gen_emoji.py - do not edit */\n"
                "#pragma once\n#include \"lvgl.h\"\n\n")
        for key in EMOJI:
            f.write(f"extern const lv_image_dsc_t emoji_{key};\n")


if __name__ == "__main__":
    main()
