#!/usr/bin/env python3
"""Draw the ambient screen's envelope icon and bake it as an LVGL 9 C array.

The ambient "you have mail" screen used LV_SYMBOL_ENVELOPE, which is the
stock FontAwesome glyph. This draws a friendlier one - plump body, round
corners, a heart where the flap points meet - as pure negative space on an
amber fill, so the lit-pixel count stays in glyph territory (burn-in is
the whole design constraint over there, see ui_ambient.c).

Output goes to main/ui/assets/ (ambient_envelope.c + ambient_assets.h,
RGB565A8 like the emoji, all committed); a preview.png lands next to this
script for eyeballing and is gitignored. Only needs re-running when the
drawing changes.

Usage: python3 gen_ambient_icon.py     (needs Pillow; the server venv has it)
"""
import os

from PIL import Image, ImageDraw

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "main", "ui", "assets")

W, H = 48, 40          # canvas; the envelope leaves ~3 px of AA headroom
SS = 8                 # supersample factor for clean curves at 48 px
AMBER = (0xFF, 0xB3, 0x00)   # COL_ACCENT - blue channel dark on purpose


def draw_mask() -> Image.Image:
    """Alpha mask at SSx scale: amber where 255, screen-off where 0."""
    m = Image.new("L", (W * SS, H * SS), 0)
    d = ImageDraw.Draw(m)

    def pt(x: float, y: float) -> tuple[float, float]:
        return (x * SS, y * SS)

    # plump body: 42x32, corners round enough to read as soft
    d.rounded_rectangle([pt(3, 4), pt(45, 36)], radius=9 * SS, fill=255)

    # flap: a V cut from the top corners, each line landing on a heart
    # lobe rather than the center - keeps the notch between the lobes
    # open so the heart stays a heart instead of smearing into a blob
    hx, hy, r = 24, 23, 3.9                 # heart: lobe centers +-3.0, r
    for x0, xe in ((2.5, hx - 4.0), (45.5, hx + 4.0)):
        d.line([pt(x0, 3.5), pt(xe, 20.2)], fill=0, width=int(3.0 * SS))

    # heart seal at the flap point: two lobes, then the tip
    for cx in (hx - 3.0, hx + 3.0):
        d.ellipse([pt(cx - r, hy - r), pt(cx + r, hy + r)], fill=0)
    d.polygon([pt(hx - r - 2.7, hy + 1.1), pt(hx + r + 2.7, hy + 1.1),
               pt(hx, hy + r + 4.6)], fill=0)

    return m.resize((W, H), Image.LANCZOS)


def emit(mask: Image.Image) -> None:
    r, g, b = AMBER
    v = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
    rgb, alpha = bytearray(), bytearray()
    for a in mask.getdata():
        rgb += bytes((v & 0xFF, v >> 8))          # RGB565 little-endian
        alpha.append(a)
    data = bytes(rgb + alpha)                     # color plane, then A8 plane
    lines = []
    for i in range(0, len(data), 16):
        lines.append("    " + "".join(f"0x{c:02x}," for c in data[i:i + 16]))
    body = "\n".join(lines)
    with open(os.path.join(OUT, "ambient_envelope.c"), "w") as f:
        f.write(f"""/* generated by tools/gen_ambient_icon.py - do not edit */
#include "lvgl.h"

static const uint8_t ambient_envelope_map[] = {{
{body}
}};

const lv_image_dsc_t ambient_envelope = {{
    .header = {{ .magic = LV_IMAGE_HEADER_MAGIC,
                .cf = LV_COLOR_FORMAT_RGB565A8,
                .w = {W}, .h = {H}, .stride = {W * 2} }},
    .data_size = sizeof(ambient_envelope_map),
    .data = ambient_envelope_map,
}};
""")
    with open(os.path.join(OUT, "ambient_assets.h"), "w") as f:
        f.write("/* generated by tools/gen_ambient_icon.py - do not edit */\n"
                "#pragma once\n#include \"lvgl.h\"\n\n"
                f"#define AMBIENT_ENVELOPE_W {W}\n"
                f"#define AMBIENT_ENVELOPE_H {H}\n\n"
                "extern const lv_image_dsc_t ambient_envelope;\n")


def preview(mask: Image.Image) -> None:
    """8x nearest preview on black - what a dark room sees, roughly."""
    img = Image.new("RGB", (W, H), (0, 0, 0))
    img.paste(Image.new("RGB", (W, H), AMBER), mask=mask)
    img.resize((W * 8, H * 8), Image.NEAREST).save(
        os.path.join(HERE, "preview.png"))


def main() -> None:
    os.makedirs(OUT, exist_ok=True)
    mask = draw_mask()
    lit = sum(1 for a in mask.getdata() if a >= 128)
    emit(mask)
    preview(mask)
    print(f"ambient_envelope.c  ({W}x{H} RGB565A8, {W * H * 3} bytes, "
          f"{lit} px lit = {100 * lit / (368 * 448):.2f}% of panel)")


if __name__ == "__main__":
    main()
